language: android

jdk: openjdk8

android:
  components:
    - tools
    - platform-tools
    - tools

    - build-tools-26.0.2
    - android-27

    - extra-android-m2repository
    - extra-google-m2repository

before_install:
  - openssl aes-256-cbc -K $encrypted_a9b8bf4fc451_key -iv $encrypted_a9b8bf4fc451_iv
    -in neerc.properties.enc -out neerc.properties -d
  - openssl aes-256-cbc -K $encrypted_a9b8bf4fc451_key -iv $encrypted_a9b8bf4fc451_iv
    -in app/src/main/assets/chat.bks.enc -out app/src/main/assets/chat.bks -d

addons:
  ssh_known_hosts: neerc.ifmo.ru

before_deploy:
  - openssl aes-256-cbc -K $encrypted_a9b8bf4fc451_key -iv $encrypted_a9b8bf4fc451_iv
    -in scripts/deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: scripts/deploy.sh
  on:
    tags: true
